---

- name: Download and unarchive prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy binaries and libraries
  ansible.builtin.copy:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item.src }}
    dest: "{{ item.dest }}"
    remote_src: yes
    owner: prometheus
    group: prometheus
    mode: "0750"
  with_items:
    - { src: "prometheus", dest: "/usr/local/bin/prometheus" }
    - { src: "promtool", dest: "/usr/local/bin/promtool" }
    - { src: "consoles", dest: "/etc/prometheus" }
    - { src: "console_libraries", dest: "/etc/prometheus" }

- name: Delete temporary files
  ansible.builtin.file:
    path: /tmp/prometheus-{{ prometheus_version }}.linux-amd64
    state: absent
