{
 "title": "HTTP/ICMP Checks",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Targets",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP/ICMP (Up/Down) - Current",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_success" }
   ]
  },
  {
   "title": "HTTP/ICMP (Up/Down)  - Historic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "- probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_duration_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry-time()",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}