---

- name: Create prometheus user
  ansible.builtin.user:
    name: prometheus
    system: yes
    shell: /sbin/nologin
    state: present
  register: prometheus_user

- name: Create prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0744"
  with_items:
    - "/etc/prometheus"
    - "/var/lib/prometheus"
